
-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('DEFAULT', 'DOCTOR', 'ASESINO', 'FISCAL', 'DETECTIVE', 'MANIACO', 'PERIODISTA');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "gamesWonAsDetective" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gamesWonAsDoctor" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gamesWonAsJournalist" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gamesWonAsLawyer" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gamesWonAsManiac" INTEGER NOT NULL DEFAULT 0,
DROP COLUMN "role",
ADD COLUMN     "role" "UserRole" NOT NULL;
